# Generated by Django 5.0.6 on 2024-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetmedicale', '0002_appointment_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='matricule',
            field=models.IntegerField(max_length=20),
        ),
    ]
