# Generated by Django 5.0.6 on 2024-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetmedicale', '0007_remove_patient_id_sign_up_doctor_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
