# Generated by Django 5.0.6 on 2024-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetmedicale', '0008_remove_doctor_doctor_name_patient_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_sign_up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
