# Generated by Django 5.0.6 on 2024-05-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetmedicale', '0009_patient_id_sign_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id_sign_up',
        ),
    ]
